apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: 29092
      targetPort: 29092
    - name: kafka-external
      port: 9092
      targetPort: 9092
    - name: kafka-metrics
      port: 9101
      targetPort: 9101
  selector:
    app: kafka-broker
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-external
spec:
  type: NodePort
  ports:
    - name: kafka-external
      port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
        - name: broker
          image: confluentinc/confluent-local:7.4.1
          ports:
            - containerPort: 29092
            - containerPort: 9092
            - containerPort: 9101
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-broker:29093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://kafka-broker:29092,CONTROLLER://kafka-broker:29093,PLAINTEXT_HOST://0.0.0.0:9092"