apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tilt
spec:
  selector:
    matchLabels:
      app: hello-tilt
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-tilt
    spec:
      containers:
      - name: hello-tilt
        image: hello-tilt
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3