apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
  labels:
    app: hellotilt

data:
  KAFKA_BROKER: "broker:29092"
  KAFKA_TOPIC: "weather_updates"
  KAFKA_GROUP_ID: "weather-consumer-group"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellotilt
spec:
  selector:
    matchLabels:
      app: hellotilt
  replicas: 1
  template:
    metadata:
      labels:
        app: hellotilt
    spec:
      containers:
      - name: hellotilt
        image: hellotilt
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_BROKER
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_TOPIC
        - name: KAFKA_GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_GROUP_ID
        readinessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 15
        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3