services:
  broker:
    image: confluentinc/confluent-local:7.4.1
    hostname: broker
    container_name: broker
    ports:
      - "8082:8082"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'

  create-topic:
    image: confluentinc/cp-kafka:7.4.1
    depends_on:
      - broker
    entrypoint: ["/bin/sh", "-c"]
    command: |
      
      # Wait for Kafka to be ready
      cub kafka-ready -b broker:29092 1 20 && \
      kafka-topics --create --if-not-exists --bootstrap-server broker:29092 --topic weather_updates --replication-factor 1 --partitions 1
