apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tilt
spec:
  selector:
    matchLabels:
      app: hello-tilt
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-tilt
    spec:
      containers:
      - name: hello-tilt
        image: hello-tilt
        ports:
        - containerPort: 80