docker_build('hello-tilt', './hello-tilt')
k8s_yaml(kustomize('overlays/port'))
k8s_resource('hello-tilt', port_forwards='80:80')

local_resource(
    'smoke-test-weatherforecast',
    'curl --fail http://localhost:80/weatherforecast',
    deps=[],
)
