apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tilt
spec:
  selector:
    matchLabels:
      app: hello-tilt
  template:
    spec:
      containers:
      - name: hello-tilt
        ports:
        - containerPort: 8081 