apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellotilt
spec:
  selector:
    matchLabels:
      app: hellotilt
  template:
    spec:
      containers:
      - name: hellotilt
        ports:
        - containerPort: 8081 