apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
  labels:
    app: hellotilt
data:
  KAFKA_BROKER: "localhost:29092"
  KAFKA_TOPIC: "weather_updates"
  KAFKA_GROUP_ID: "weather-consumer-group"